// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5yqdg9HU1e84wET0ySIpph6-ml5N2V60',
    appId: '1:259663716394:web:7eb8c98600abdfd6616353',
    messagingSenderId: '259663716394',
    projectId: 'nawalt-auth',
    authDomain: 'nawalt-auth.firebaseapp.com',
    storageBucket: 'nawalt-auth.appspot.com',
    measurementId: 'G-8PRJJ8K3PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMreyBXmcBryAkUm-2MMB3xKp00b7NUzE',
    appId: '1:259663716394:android:a646db67f87a4367616353',
    messagingSenderId: '259663716394',
    projectId: 'nawalt-auth',
    storageBucket: 'nawalt-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAjx6emjDYAgeTOWB8g2F0o0NqnaYVp10',
    appId: '1:259663716394:ios:1406a61fd3d2a1e2616353',
    messagingSenderId: '259663716394',
    projectId: 'nawalt-auth',
    storageBucket: 'nawalt-auth.appspot.com',
    iosBundleId: 'com.nawalt.trace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAjx6emjDYAgeTOWB8g2F0o0NqnaYVp10',
    appId: '1:259663716394:ios:66544a9226f30d17616353',
    messagingSenderId: '259663716394',
    projectId: 'nawalt-auth',
    storageBucket: 'nawalt-auth.appspot.com',
    iosBundleId: 'com.nawalt.trace.RunnerTests',
  );
}
